name: CI/CD
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  ci:
    name: CI
    uses: udibo/react_app/.github/workflows/ci.yml@0.11.0
    with:
      test-args: '-A'
  cd:
    name: CD
    needs: ci
    uses: udibo/react_app/.github/workflows/deploy.yml@0.11.0
    with:
      project: udibo-react-app-example
